#!/usr/bin/env bash
set -u -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
ARTIFACTS_DIR="${ROOT_DIR}/artifacts"

usage() {
  cat <<'EOF'
Usage: ./scripts/analyze_snapshot.sh [snapshot_dir]

Analyze a snapshot generated by collect_snapshot.sh.
If snapshot_dir is omitted, the latest snapshot is used.
EOF
}

if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
  usage
  exit 0
fi

if [ $# -gt 1 ]; then
  usage >&2
  exit 1
fi

if [ $# -eq 1 ]; then
  SNAPSHOT_DIR="$1"
else
  if [ -L "${ARTIFACTS_DIR}/latest" ] || [ -d "${ARTIFACTS_DIR}/latest" ]; then
    SNAPSHOT_DIR="$(cd "${ARTIFACTS_DIR}" && pwd)/$(readlink "${ARTIFACTS_DIR}/latest")"
  else
    SNAPSHOT_DIR="$(ls -1dt "${ARTIFACTS_DIR}"/snapshot-* 2>/dev/null | head -n 1 || true)"
  fi
fi

if [ -z "${SNAPSHOT_DIR}" ] || [ ! -d "${SNAPSHOT_DIR}" ]; then
  echo "No snapshot found to analyze." >&2
  exit 1
fi

COMMANDS_DIR="${SNAPSHOT_DIR}/commands"
SUMMARY_FILE="${SNAPSHOT_DIR}/analysis-summary.md"

if [ ! -d "${COMMANDS_DIR}" ]; then
  echo "Invalid snapshot: missing commands directory: ${COMMANDS_DIR}" >&2
  exit 1
fi

mapfile -t LOG_FILES < <(find "${COMMANDS_DIR}" -maxdepth 1 -type f | sort)

if [ "${#LOG_FILES[@]}" -eq 0 ]; then
  echo "No command output files found in ${COMMANDS_DIR}" >&2
  exit 1
fi

render_header() {
  {
    echo "# Crash Analysis Summary"
    echo
    echo "- Snapshot: ${SNAPSHOT_DIR}"
    echo "- Generated: $(date --iso-8601=seconds)"
    echo
  } >"${SUMMARY_FILE}"
}

render_collection_health() {
  local failures
  failures="$(grep -H '^# Exit status: [1-9]' "${COMMANDS_DIR}"/*.txt 2>/dev/null || true)"

  {
    echo "## Collection Health"
    if [ -n "${failures}" ]; then
      echo
      echo "Some collection commands returned non-zero exit statuses."
      echo "This is usually due to permissions or missing commands."
      echo
      printf '%s\n' '```text'
      echo "${failures}" | sed "s|${COMMANDS_DIR}/||g"
      printf '%s\n' '```'
    else
      echo
      echo "All collection commands exited with status 0."
    fi
    echo
  } >>"${SUMMARY_FILE}"
}

collect_matches() {
  local regex="$1"
  shift || true

  if [ $# -gt 0 ]; then
    grep -HnEi "${regex}" "$@" 2>/dev/null || true
  else
    grep -HnEi "${regex}" "${LOG_FILES[@]}" 2>/dev/null || true
  fi
}

count_matches() {
  local regex="$1"
  shift || true
  local matches

  matches="$(collect_matches "${regex}" "$@")"
  printf '%s\n' "${matches}" | sed '/^$/d' | wc -l | tr -d ' '
}

payload_lines() {
  local file="$1"
  [ -f "${file}" ] || return 0
  grep -vE '^(# |$|SKIPPED:|MISSING:)' "${file}" 2>/dev/null || true
}

count_payload_lines() {
  local file="$1"
  local exclude_regex="${2:-}"
  local lines

  lines="$(payload_lines "${file}")"
  if [ -n "${exclude_regex}" ]; then
    lines="$(printf '%s\n' "${lines}" | grep -Eiv "${exclude_regex}" 2>/dev/null || true)"
  fi
  printf '%s\n' "${lines}" | sed '/^$/d' | wc -l | tr -d ' '
}

append_pattern_section() {
  local label="$1"
  local regex="$2"
  local matches
  local count

  matches="$(collect_matches "${regex}")"
  count="$(count_matches "${regex}")"

  {
    echo "## ${label}"
    echo
    echo "- Matches: ${count}"
    if [ "${count}" -gt 0 ]; then
      echo
      printf '%s\n' '```text'
      printf '%s\n' "${matches}" | sed "s|${COMMANDS_DIR}/||g" | sed -n '1,25p'
      printf '%s\n' '```'
    fi
    echo
  } >>"${SUMMARY_FILE}"
}

append_pattern_section_from_files() {
  local label="$1"
  local regex="$2"
  shift 2
  local matches
  local count

  matches="$(collect_matches "${regex}" "$@")"
  count="$(printf '%s\n' "${matches}" | sed '/^$/d' | wc -l | tr -d ' ')"

  {
    echo "## ${label}"
    echo
    echo "- Matches: ${count}"
    if [ "${count}" -gt 0 ]; then
      echo
      printf '%s\n' '```text'
      printf '%s\n' "${matches}" | sed "s|${COMMANDS_DIR}/||g" | sed -n '1,25p'
      printf '%s\n' '```'
    fi
    echo
  } >>"${SUMMARY_FILE}"
}

read_kv_value() {
  local file="$1"
  local key="$2"
  if [ ! -f "${file}" ]; then
    return 0
  fi
  awk -v key="${key}" 'index($0, key "=") == 1 {print substr($0, length(key) + 2); exit}' "${file}" 2>/dev/null
}

extract_findmnt_options() {
  local target="$1"
  local file="${COMMANDS_DIR}/findmnt.txt"
  if [ ! -f "${file}" ]; then
    return 0
  fi
  awk -v target="${target}" '
    {
      mount_target = $1
      sub(/^[^/]+/, "", mount_target)
      if (mount_target == target) {
        print $NF
        exit
      }
    }
  ' "${file}" 2>/dev/null
}

mount_mode_from_options() {
  local options="$1"
  case ",${options}," in
    *,ro,*) echo "ro" ;;
    *,rw,*) echo "rw" ;;
    *) echo "unknown" ;;
  esac
}

boot_label_from_index() {
  case "$1" in
    0) echo "current" ;;
    -1) echo "prev-1" ;;
    -2) echo "prev-2" ;;
    *) echo "$1" ;;
  esac
}

boot_warn_file_for_index() {
  case "$1" in
    0) printf '%s\n' "${COMMANDS_DIR}/journal-current-warn.txt" ;;
    -1) printf '%s\n' "${COMMANDS_DIR}/journal-prev-warn.txt" ;;
    -2) printf '%s\n' "${COMMANDS_DIR}/journal-prev2-warn.txt" ;;
    *) return 1 ;;
  esac
}

boot_window_from_list() {
  local idx="$1"
  local file="${COMMANDS_DIR}/journal-list-boots.txt"
  if [ ! -f "${file}" ]; then
    return 0
  fi

  awk -v idx="${idx}" '
    $1 == idx {
      sub(/^[[:space:]]+/, "", $0)
      print
      exit
    }
  ' "${file}" 2>/dev/null
}

count_session_entries() {
  local file="$1"
  local section_header="$2"

  if [ ! -f "${file}" ]; then
    echo "0"
    return 0
  fi

  awk -v section_header="${section_header}" '
    $0 == section_header {
      in_section = 1
      next
    }
    /^# / && in_section {
      exit
    }
    in_section && NF && $0 !~ /^MISSING:/ {
      count++
    }
    END {
      print count + 0
    }
  ' "${file}" 2>/dev/null
}

rpm_query_pkg_state() {
  local file="$1"
  local pkg="$2"

  if [ ! -f "${file}" ]; then
    echo "unknown"
    return 0
  fi

  if grep -Eq "^${pkg}-[0-9]" "${file}" 2>/dev/null; then
    echo "installed"
  elif grep -Eq "^package ${pkg} is not installed" "${file}" 2>/dev/null; then
    echo "missing"
  else
    echo "unknown"
  fi
}

collect_nvidia_invalid_mmap_bursts() {
  local file

  for file in "$@"; do
    [ -f "${file}" ] || continue

    awk -v prefix="${file}" '
      /NVRM: VM: invalid mmap/ {
        ts = $1 " " $2 " " $3
        if (count > 0 && ts == last_ts) {
          count++
          next
        }
        if (count > 0) {
          printf "%s:%d:%s: NVRM: VM: invalid mmap (burst x%d)\n", prefix, first_line, last_ts, count
        }
        last_ts = ts
        first_line = FNR
        count = 1
        next
      }
      count > 0 {
        printf "%s:%d:%s: NVRM: VM: invalid mmap (burst x%d)\n", prefix, first_line, last_ts, count
        count = 0
        last_ts = ""
      }
      END {
        if (count > 0) {
          printf "%s:%d:%s: NVRM: VM: invalid mmap (burst x%d)\n", prefix, first_line, last_ts, count
        }
      }
    ' "${file}" 2>/dev/null
  done
}

count_nvidia_invalid_mmap_bursts() {
  local bursts

  bursts="$(collect_nvidia_invalid_mmap_bursts "$@")"
  printf '%s\n' "${bursts}" | sed '/^$/d' | wc -l | tr -d ' '
}

collect_gdm_idle_suspend_windows() {
  local file="$1"
  local line
  local timestamp
  local marker_timestamp=""
  local marker_epoch=""
  local marker_label=""
  local request_epoch
  local elapsed
  local manual_request=0

  [ -f "${file}" ] || return 0

  while IFS= read -r line; do
    timestamp="${line%% *}"

    case "${line}" in
      "-- Boot "*)
        marker_timestamp=""
        marker_epoch=""
        marker_label=""
        manual_request=0
        ;;
      *"New session "*"gdm-greeter"*)
        marker_timestamp="${timestamp}"
        marker_epoch="$(date -d "${timestamp}" +%s 2>/dev/null || true)"
        marker_label="GDM greeter start"
        manual_request=0
        ;;
      *"PM: suspend exit"*|*"System returned from sleep operation"*)
        marker_timestamp="${timestamp}"
        marker_epoch="$(date -d "${timestamp}" +%s 2>/dev/null || true)"
        marker_label="resume"
        manual_request=0
        ;;
      *"Power key pressed"*|*"Suspend key pressed"*|*"Lid closed"*)
        manual_request=1
        ;;
      *"The system will suspend now!"*)
        request_epoch="$(date -d "${timestamp}" +%s 2>/dev/null || true)"
        if [ -n "${marker_epoch}" ] && [ -n "${request_epoch}" ] && [ "${manual_request}" -eq 0 ]; then
          elapsed=$((request_epoch - marker_epoch))
          if [ "${elapsed}" -ge 840 ] && [ "${elapsed}" -le 1260 ]; then
            printf '%s -> %s (%ss): %s -> suspend request\n' \
              "${marker_timestamp}" "${timestamp}" "${elapsed}" "${marker_label}"
          fi
        fi
        marker_timestamp=""
        marker_epoch=""
        marker_label=""
        manual_request=0
        ;;
    esac
  done <"${file}"
}

render_suspend_triage() {
  local events_file="${COMMANDS_DIR}/journal-suspend-events.txt"
  local overrides_file="${COMMANDS_DIR}/gdm-power-overrides.txt"
  local profile_file="${COMMANDS_DIR}/gdm-dconf-profile.txt"
  local suspend_count
  local resume_count
  local input_count
  local gdm_start_count
  local idle_windows
  local idle_window_count
  local gdm_override_state
  local gdm_profile_state

  suspend_count="$(count_matches "the system will suspend now" "${events_file}")"
  resume_count="$(count_matches "pm: suspend exit|system returned from sleep operation" "${events_file}")"
  input_count="$(count_matches "power key pressed|suspend key pressed|lid closed" "${events_file}")"
  gdm_start_count="$(count_matches "new session .*gdm-greeter" "${events_file}")"
  idle_windows="$(collect_gdm_idle_suspend_windows "${events_file}")"
  idle_window_count="$(printf '%s\n' "${idle_windows}" | sed '/^$/d' | wc -l | tr -d ' ')"

  if [ -f "${overrides_file}" ] \
    && grep -Eq "^sleep-inactive-ac-timeout=0$" "${overrides_file}" 2>/dev/null \
    && grep -Eq "^sleep-inactive-ac-type='nothing'$" "${overrides_file}" 2>/dev/null \
    && grep -Eq "^sleep-inactive-battery-timeout=0$" "${overrides_file}" 2>/dev/null \
    && grep -Eq "^sleep-inactive-battery-type='nothing'$" "${overrides_file}" 2>/dev/null; then
    gdm_override_state="complete"
  elif [ -f "${overrides_file}" ] && grep -Eq "sleep-inactive-(ac|battery)-(timeout|type)" "${overrides_file}" 2>/dev/null; then
    gdm_override_state="partial"
  elif [ -f "${overrides_file}" ]; then
    gdm_override_state="not present"
  else
    gdm_override_state="not captured"
  fi

  if [ -f "${profile_file}" ] && grep -Eq '^system-db:gdm$' "${profile_file}" 2>/dev/null; then
    gdm_profile_state="active"
  elif [ -f "${profile_file}" ]; then
    gdm_profile_state="not active"
  else
    gdm_profile_state="not captured"
  fi

  {
    echo "## Suspend Triage"
    echo
    echo "- Suspend requests captured: ${suspend_count}"
    echo "- Resume events captured: ${resume_count}"
    echo "- Power/suspend-key or lid events captured: ${input_count}"
    echo "- GDM greeter starts captured: ${gdm_start_count}"
    echo "- GDM/default-idle timing matches: ${idle_window_count}"
    echo "- GDM system dconf profile: ${gdm_profile_state}"
    echo "- GDM no-auto-suspend override: ${gdm_override_state}"
    echo

    if [ "${idle_window_count}" -gt 0 ]; then
      echo "Likely cluster:"
      if [ "${idle_window_count}" -ge 2 ]; then
        echo "- Repeated suspend requests occur about 15 minutes after GDM starts or the machine resumes, strongly indicating the GDM greeter's default idle-suspend policy."
      else
        echo "- A suspend request occurred about 15 minutes after GDM started or the machine resumed, consistent with the GDM greeter's default idle-suspend policy."
      fi
      echo "- Terminal, SSH, and TTY activity does not reset the graphical GDM greeter's idle timer."
      if [ "${gdm_override_state}" != "complete" ]; then
        echo "- Install the repo's GDM-only override with: sudo ./scripts/install_gdm_no_auto_suspend.sh"
      fi
      if [ "${input_count}" -gt 0 ]; then
        echo "- Physical key/lid events also exist in the captured history, but the timing matches below exclude those events."
      fi
      echo
      printf '%s\n' '```text'
      printf '%s\n' "${idle_windows}" | sed -n '1,25p'
      printf '%s\n' '```'
      echo
    elif [ "${suspend_count}" -gt 0 ]; then
      echo "Suspend requests were captured, but they do not yet form a repeated GDM/default-idle timing pattern."
      echo
    fi
  } >>"${SUMMARY_FILE}"
}

render_resume_context() {
  local reboot_matches
  local reboot_count
  local session_regex
  local session_matches
  local session_count

  reboot_matches=""
  if [ -f "${COMMANDS_DIR}/last-reboots.txt" ]; then
    reboot_matches="$(
      awk 'NR <= 10 && /crash|gone - no logout/ {print "last-reboots.txt:" NR ":" $0}' \
        "${COMMANDS_DIR}/last-reboots.txt" 2>/dev/null || true
    )"
  fi
  reboot_count="$(printf '%s\n' "${reboot_matches}" | sed '/^$/d' | wc -l | tr -d ' ')"

  session_regex="process [0-9]+ \\(gnome-shell\\) of user [0-9]+ dumped core|org\\.gnome\\.Shell@wayland\\.service: (main process exited|failed with result)|the wayland connection broke|user@[0-9]+\\.service: main process exited, code=dumped|process [0-9]+ \\(gnome-session-i\\) of user [0-9]+ dumped core"
  session_matches="$(collect_matches "${session_regex}" "${COMMANDS_DIR}/journal-current-warn.txt" "${COMMANDS_DIR}/journal-prev-warn.txt")"
  session_count="$(printf '%s\n' "${session_matches}" | sed '/^$/d' | wc -l | tr -d ' ')"

  {
    echo "## Resume Context"
    echo
    echo "- Recent reboot/crash markers: ${reboot_count}"
    echo "- Compositor/session crash markers near the latest reboot: ${session_count}"
    echo

    if [ "${reboot_count}" -gt 0 ] || [ "${session_count}" -gt 0 ]; then
      echo "Likely cluster:"
      if [ "${reboot_count}" -gt 0 ]; then
        echo "- The latest boot followed an unclean shutdown/crash rather than a clean reboot."
      fi
      if [ "${session_count}" -gt 0 ]; then
        echo "- The previous user session appears to have died with a Wayland/GNOME Shell compositor crash."
      fi
      echo
      printf '%s\n' '```text'
      if [ "${reboot_count}" -gt 0 ]; then
        printf '%s\n' "${reboot_matches}"
      fi
      if [ "${session_count}" -gt 0 ]; then
        printf '%s\n' "${session_matches}" | sed "s|${COMMANDS_DIR}/||g" | sed -n '1,10p'
      fi
      printf '%s\n' '```'
      echo
    fi
  } >>"${SUMMARY_FILE}"
}

render_recent_reboot_triage() {
  local boot_idx
  local boot_file
  local boot_label
  local boot_window
  local codium_regex
  local session_regex
  local wayland_regex
  local nvidia_fault_regex
  local nvidia_mmap_regex
  local compiler_regex
  local memory_fault_regex
  local storage_regex
  local combined_regex
  local codium_count
  local session_count
  local wayland_count
  local nvidia_fault_count
  local nvidia_mmap_burst_count
  local compiler_fault_count
  local storage_count
  local boot_matches
  local analyzed_boots=0
  local summary_rows=""
  local notable_matches=""

  codium_regex="traps: codium|codium\\[[0-9]+\\].*(trap int3|invalid opcode|general protection fault)|process [0-9]+ \\(codium\\) of user [0-9]+ dumped core|/usr/share/codium/codium.*sig(segv|trap|ill)"
  session_regex="process [0-9]+ \\(gnome-shell\\) of user [0-9]+ dumped core|org\\.gnome\\.Shell@wayland\\.service: (main process exited|failed with result)|the wayland connection broke|user@[0-9]+\\.service: main process exited, code=dumped|process [0-9]+ \\(gnome-session-i\\) of user [0-9]+ dumped core"
  wayland_regex="connection to xwayland lost|invalid sequence for vsync frame info|the wayland connection broke|cannot open display: :0|qt\\.qpa\\.wayland"
  nvidia_fault_regex="nvrm: xid|nvidia-drm.*error|gpu has fallen off|nvidia-smi has failed|failed to initialize nvml"
  nvidia_mmap_regex="nvrm: vm: invalid mmap"
  compiler_regex="internal compiler error|/usr/libexec/gcc/.*/cc1|comm: cc1|terminated abnormally without generating a coredump"
  memory_fault_regex="corrupted page table|bad pagetable|oops:|exited with irqs disabled"
  storage_regex="btrfs|ext4-fs error|xfs|nvme.*error|read-only file system|remount-ro"
  combined_regex="${codium_regex}|${session_regex}|${wayland_regex}|${nvidia_fault_regex}|${nvidia_mmap_regex}|${compiler_regex}|${memory_fault_regex}|${storage_regex}"

  for boot_idx in 0 -1 -2; do
    boot_file="$(boot_warn_file_for_index "${boot_idx}" || true)"
    boot_label="$(boot_label_from_index "${boot_idx}")"
    boot_window="$(boot_window_from_list "${boot_idx}")"

    if [ -z "${boot_window}" ] && { [ -z "${boot_file}" ] || [ ! -f "${boot_file}" ]; }; then
      continue
    fi

    analyzed_boots=$((analyzed_boots + 1))
    codium_count="$(count_matches "${codium_regex}" "${boot_file}")"
    session_count="$(count_matches "${session_regex}" "${boot_file}")"
    wayland_count="$(count_matches "${wayland_regex}" "${boot_file}")"
    nvidia_fault_count="$(count_matches "${nvidia_fault_regex}" "${boot_file}")"
    nvidia_mmap_burst_count="$(count_nvidia_invalid_mmap_bursts "${boot_file}")"
    compiler_fault_count="$(count_matches "${compiler_regex}" "${boot_file}")"
    memory_fault_count="$(count_matches "${memory_fault_regex}" "${boot_file}")"
    storage_count="$(count_matches "${storage_regex}" "${boot_file}")"

    summary_rows="${summary_rows}boot ${boot_label} (${boot_idx}) | ${boot_window:-boot metadata unavailable}\n"
    summary_rows="${summary_rows}  indicators: codium=${codium_count} compositor=${session_count} wayland=${wayland_count} nvidia_faults=${nvidia_fault_count} nvidia_vm_bursts=${nvidia_mmap_burst_count} compiler_faults=${compiler_fault_count} mem_faults=${memory_fault_count} storage=${storage_count}\n"

    boot_matches="$(collect_matches "${combined_regex}" "${boot_file}")"
    if [ -n "${boot_matches}" ]; then
      notable_matches="${notable_matches}# boot ${boot_label} (${boot_idx})\n"
      notable_matches="${notable_matches}$(printf '%s\n' "${boot_matches}" | sed "s|${COMMANDS_DIR}/||g" | sed -n '1,4p')\n"
    fi
  done

  {
    echo "## Recent Reboot Triage"
    echo
    echo "- Boots analyzed: ${analyzed_boots}"
    echo "- Scope: current boot plus the previous two boots when captured"
    echo

    if [ -n "${summary_rows}" ]; then
      printf '%s\n' '```text'
      printf '%b' "${summary_rows}"
      printf '%s\n' '```'
      echo
    fi

    if [ -n "${notable_matches}" ]; then
      echo "Notable matches:"
      echo
      printf '%s\n' '```text'
      printf '%b' "${notable_matches}"
      printf '%s\n' '```'
      echo
    fi
  } >>"${SUMMARY_FILE}"
}

render_xorg_comparison_readiness() {
  local session_file="${COMMANDS_DIR}/display-session-files.txt"
  local pkg_file="${COMMANDS_DIR}/rpm-display-session-packages.txt"
  local gdm_conf_file="${COMMANDS_DIR}/gdm-custom-conf.txt"
  local xsession_count
  local wayland_session_count
  local xorg_server_state
  local gnome_xsession_state
  local gdm_wayland_disabled="no"
  local comparison_ready="no"

  xsession_count="$(count_session_entries "${session_file}" "# /usr/share/xsessions")"
  wayland_session_count="$(count_session_entries "${session_file}" "# /usr/share/wayland-sessions")"
  xorg_server_state="$(rpm_query_pkg_state "${pkg_file}" "xorg-x11-server-Xorg")"
  gnome_xsession_state="$(rpm_query_pkg_state "${pkg_file}" "gnome-session-xsession")"

  if [ -f "${gdm_conf_file}" ] && grep -Eq '^[[:space:]]*WaylandEnable=false([[:space:]]*|$)' "${gdm_conf_file}" 2>/dev/null; then
    gdm_wayland_disabled="yes"
  fi

  if [ "${xsession_count}" -gt 0 ] && [ "${xorg_server_state}" = "installed" ]; then
    comparison_ready="yes"
  fi

  {
    echo "## Xorg Comparison Readiness"
    echo
    echo "- Xorg session entries detected: ${xsession_count}"
    echo "- Wayland session entries detected: ${wayland_session_count}"
    echo "- Xorg server package state: ${xorg_server_state}"
    echo "- GNOME Xorg session package state: ${gnome_xsession_state}"
    echo "- GDM login screen forced off Wayland: ${gdm_wayland_disabled}"
    echo "- Xorg comparison ready on this host: ${comparison_ready}"
    echo

    if [ "${comparison_ready}" = "yes" ]; then
      echo "Likely cluster:"
      echo "- A GDM session-menu comparison between Wayland and Xorg should be possible on this host."
      echo
    elif [ -f "${session_file}" ] || [ -f "${pkg_file}" ] || [ -f "${gdm_conf_file}" ]; then
      echo "Likely cluster:"
      echo "- This host does not currently expose an Xorg login option for comparison."
      if [ "${xorg_server_state}" = "missing" ]; then
        echo "- The Xorg server package is not installed."
      fi
      if [ "${xsession_count}" -eq 0 ]; then
        echo "- No Xorg desktop entries were captured under /usr/share/xsessions."
      fi
      echo
      printf '%s\n' '```text'
      if [ -f "${session_file}" ]; then
        sed "s|${COMMANDS_DIR}/||g" "${session_file}" | sed -n '1,20p'
      fi
      if [ -f "${pkg_file}" ]; then
        sed "s|${COMMANDS_DIR}/||g" "${pkg_file}" | sed -n '1,10p'
      fi
      if [ -f "${gdm_conf_file}" ]; then
        sed "s|${COMMANDS_DIR}/||g" "${gdm_conf_file}" | sed -n '1,20p'
      fi
      printf '%s\n' '```'
      echo
    fi
  } >>"${SUMMARY_FILE}"
}

render_historical_coredump_trends() {
  local coredump_file="${COMMANDS_DIR}/coredump-list.txt"
  local top_rows=""
  local codium_count=0
  local gnome_shell_count=0
  local xwayland_count=0
  local firefox_count=0
  local spotify_count=0
  local gcc_cc1_count=0
  local recurring_focus_count=0

  if [ -f "${coredump_file}" ]; then
    top_rows="$(
      awk '
        NF >= 10 && $1 != "TIME" && $1 !~ /^#/ {
          exe = $10
          count[exe]++
          latest[exe] = $1 " " $2 " " $3 " " $4
        }
        END {
          for (exe in count) {
            printf "%4d | %s | %s\n", count[exe], latest[exe], exe
          }
        }
      ' "${coredump_file}" 2>/dev/null | sort -nr | sed -n '1,10p'
    )"

    codium_count="$(grep -cF '/usr/share/codium/codium' "${coredump_file}" 2>/dev/null || true)"
    gnome_shell_count="$(grep -cF '/usr/bin/gnome-shell' "${coredump_file}" 2>/dev/null || true)"
    xwayland_count="$(grep -cF '/usr/bin/Xwayland' "${coredump_file}" 2>/dev/null || true)"
    firefox_count="$(grep -cF '/usr/lib64/firefox/firefox' "${coredump_file}" 2>/dev/null || true)"
    spotify_count="$(grep -Ec '/snap/spotify/.*/spotify' "${coredump_file}" 2>/dev/null || true)"
    gcc_cc1_count="$(grep -Ec '/usr/libexec/gcc/.*/cc1' "${coredump_file}" 2>/dev/null || true)"

    for count in "${codium_count}" "${gnome_shell_count}" "${xwayland_count}" "${firefox_count}" "${spotify_count}" "${gcc_cc1_count}"; do
      if [ "${count}" -gt 0 ]; then
        recurring_focus_count=$((recurring_focus_count + 1))
      fi
    done
  fi

  {
    echo "## Historical Coredump Trends"
    echo
    echo "- Coredump history captured: $([ -f "${coredump_file}" ] && echo yes || echo no)"
    echo "- Codium coredumps recorded: ${codium_count}"
    echo "- GNOME Shell coredumps recorded: ${gnome_shell_count}"
    echo "- Xwayland coredumps recorded: ${xwayland_count}"
    echo "- Firefox coredumps recorded: ${firefox_count}"
    echo "- Spotify coredumps recorded: ${spotify_count}"
    echo "- GCC cc1 coredumps recorded: ${gcc_cc1_count}"
    echo

    if [ -n "${top_rows}" ]; then
      echo "Likely cluster:"
      if [ "${codium_count}" -gt 0 ] && [ "${gnome_shell_count}" -gt 0 ]; then
        echo "- Codium is recurrent, but the compositor also has an independent crash history."
      fi
      if [ "${recurring_focus_count}" -ge 3 ]; then
        echo "- Multiple unrelated GUI apps have historical coredumps, which points to broader session/display/platform instability rather than a single bad app profile."
      fi
      echo
      printf '%s\n' '```text'
      printf '%s\n' "${top_rows}"
      printf '%s\n' '```'
      echo
    fi
  } >>"${SUMMARY_FILE}"
}


gpu_pcie_link_rows() {
  local file="${COMMANDS_DIR}/gpu-pcie-links.txt"
  [ -f "${file}" ] || return 0

  awk '
    function flush() {
      if (device == "") {
        return
      }
      current_width_num = current_width + 0
      max_width_num = max_width + 0
      degraded = "no"
      if (current_width_num > 0 && max_width_num > 0 && current_width_num < max_width_num) {
        degraded = "yes"
      }
      speed_downshift = "no"
      if (current_speed != "" && max_speed != "" && current_speed != max_speed) {
        speed_downshift = "yes"
      }
      printf "%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n", device, driver, current_width, max_width, current_speed, max_speed, degraded, speed_downshift, subsystem_vendor ":" subsystem_device
    }
    /^pci_device=/ { flush(); device = substr($0, 12); driver = ""; current_width = ""; max_width = ""; current_speed = ""; max_speed = ""; subsystem_vendor = ""; subsystem_device = ""; next }
    /^driver=/ { driver = substr($0, 8); next }
    /^current_link_width=/ { current_width = substr($0, 20); next }
    /^max_link_width=/ { max_width = substr($0, 16); next }
    /^current_link_speed=/ { current_speed = substr($0, 20); next }
    /^max_link_speed=/ { max_speed = substr($0, 16); next }
    /^subsystem_vendor=/ { subsystem_vendor = substr($0, 18); next }
    /^subsystem_device=/ { subsystem_device = substr($0, 18); next }
    END { flush() }
  ' "${file}"
}

count_gpu_pcie_links() {
  gpu_pcie_link_rows | sed '/^$/d' | wc -l | tr -d ' '
}

count_degraded_gpu_pcie_links() {
  gpu_pcie_link_rows | awk -F '\t' '$7 == "yes" { count++ } END { print count + 0 }'
}

count_downshifted_gpu_pcie_speeds() {
  gpu_pcie_link_rows | awk -F '\t' '$8 == "yes" { count++ } END { print count + 0 }'
}

render_gpu_pcie_link_evaluation() {
  local link_count
  local degraded_count
  local downshifted_count
  local rows

  rows="$(gpu_pcie_link_rows)"
  link_count="$(printf '%s\n' "${rows}" | sed '/^$/d' | wc -l | tr -d ' ')"
  degraded_count="$(printf '%s\n' "${rows}" | awk -F '\t' '$7 == "yes" { count++ } END { print count + 0 }')"
  downshifted_count="$(printf '%s\n' "${rows}" | awk -F '\t' '$8 == "yes" { count++ } END { print count + 0 }')"

  {
    echo "## GPU PCIe Link Evaluation"
    echo
    echo "- GPU PCIe links captured: ${link_count}"
    echo "- Degraded GPU link widths: ${degraded_count}"
    echo "- Link-speed downshifts captured: ${downshifted_count}"
    echo
    if [ "${link_count}" -gt 0 ]; then
      printf '%s\n' '```text'
      printf '%s\n' "${rows}" | awk -F '\t' '{ printf "%s driver=%s width=%s/%s speed=%s/%s degraded_width=%s speed_downshift=%s subsystem=%s\n", $1, ($2 == "" ? "unknown" : $2), ($3 == "" ? "unknown" : $3 "x"), ($4 == "" ? "unknown" : $4 "x"), ($5 == "" ? "unknown" : $5), ($6 == "" ? "unknown" : $6), $7, $8, $9 }'
      printf '%s\n' '```'
      echo
    fi
    if [ "${degraded_count}" -gt 0 ]; then
      echo "Likely cluster:"
      echo "- One or more GPUs negotiated fewer PCIe lanes than the device reports as its maximum. Unlike PCIe speed downshift, lane-width degradation is not expected as a normal idle power-saving state. Confirm under load and inspect slot/riser/BIOS settings if it persists."
      echo
    elif [ "${downshifted_count}" -gt 0 ]; then
      echo "Likely cluster:"
      echo "- PCIe speed is currently below the maximum, which can be normal while the GPU is idle. Re-check under load before treating speed alone as a fault."
      echo
    fi
  } >>"${SUMMARY_FILE}"
}


probe_value() {
  local file="$1"
  local key="$2"
  sed -n "s/^${key}=//p" "${file}" 2>/dev/null | tail -n 1
}

render_gpu_pcie_load_probe() {
  local file="${COMMANDS_DIR}/gpu-pcie-load-probe.txt"
  [ -f "${file}" ] || return 0

  local workload_label
  local workload_status
  local link_count
  local degraded_before
  local degraded_during
  local speed_increased
  local observed_width
  local cap_width
  local observed_speed
  local cap_speed

  workload_label="$(probe_value "${file}" workload_label)"
  workload_status="$(probe_value "${file}" workload_status)"
  link_count="$(probe_value "${file}" result_pcie_link_count)"
  degraded_before="$(probe_value "${file}" result_width_degraded_before)"
  degraded_during="$(probe_value "${file}" result_width_degraded_during)"
  speed_increased="$(probe_value "${file}" result_speed_increased_under_load)"
  observed_width="$(probe_value "${file}" result_max_observed_width)"
  cap_width="$(probe_value "${file}" result_max_cap_width)"
  observed_speed="$(probe_value "${file}" result_max_observed_speed)"
  cap_speed="$(probe_value "${file}" result_max_cap_speed)"

  {
    echo "## GPU PCIe Load Probe"
    echo
    echo "- Workload: ${workload_label:-unknown} (${workload_status:-unknown})"
    echo "- GPU PCIe links sampled: ${link_count:-0}"
    echo "- Width degraded before load: ${degraded_before:-0}"
    echo "- Width degraded during load: ${degraded_during:-0}"
    echo "- Speed increased under load: ${speed_increased:-unknown}"
    echo "- Max observed width: ${observed_width:-unknown}x/${cap_width:-unknown}x"
    echo "- Max observed speed: ${observed_speed:-unknown}/${cap_speed:-unknown}"
    echo
    if [ "${workload_status}" = "skipped" ]; then
      echo "Likely cluster:"
      echo "- No GPU workload command was available, so this probe only sampled link state without an active load. Install glxgears, glmark2, vkmark, or set FEDORA_DEBUGG_GPU_PCIE_WORKLOAD to force a workload."
      echo
    elif [ "${degraded_during:-0}" -gt 0 ]; then
      echo "Likely cluster:"
      echo "- GPU PCIe width remained below capability during the load probe. That is stronger evidence for a lane negotiation or slot/lane allocation issue than an idle power-saving artifact."
      echo
    elif [ "${speed_increased}" = "yes" ]; then
      echo "Likely cluster:"
      echo "- PCIe speed responded to GPU load and width was not degraded during the probe."
      echo
    fi
  } >>"${SUMMARY_FILE}"
}


render_bios_pcie_topology() {
  local dmi_file="${COMMANDS_DIR}/dmi-id.txt"
  local lspci_tree_file="${COMMANDS_DIR}/lspci-tree.txt"
  local kernel_file="${COMMANDS_DIR}/journal-kernel-current.txt"
  local lspci_file="${COMMANDS_DIR}/lspci.txt"
  local board_name
  local board_vendor
  local bios_version
  local bios_date
  local gpu_bridge
  local cpu_peg_empty
  local bandwidth_lines

  board_name="$(sed -n 's/^board_name=//p' "${dmi_file}" 2>/dev/null | tail -n 1)"
  board_vendor="$(sed -n 's/^board_vendor=//p' "${dmi_file}" 2>/dev/null | tail -n 1)"
  bios_version="$(sed -n 's/^bios_version=//p' "${dmi_file}" 2>/dev/null | tail -n 1)"
  bios_date="$(sed -n 's/^bios_date=//p' "${dmi_file}" 2>/dev/null | tail -n 1)"
  gpu_bridge="$(grep -E '(^|[^0-9])1b\.4-\[03\].*NVIDIA|00:1b\.4-\[03\].*NVIDIA|(^|[^0-9])01\.0-\[01\].*NVIDIA|00:01\.0-\[01\].*NVIDIA|03:00\.0.*NVIDIA' "${lspci_tree_file}" 2>/dev/null | head -n 1 || true)"
  cpu_peg_empty="unknown"
  if grep -Eq '(^|[^0-9])01\.0-\[01\]--|00:01\.0-\[01\]--' "${lspci_tree_file}" 2>/dev/null; then
    cpu_peg_empty="yes"
  elif grep -Eiq '(^|[^0-9])01\.0-\[[^]]+\].*(NVIDIA|VGA|Display)|00:01\.0-\[[^]]+\].*(NVIDIA|VGA|Display)' "${lspci_tree_file}" 2>/dev/null; then
    cpu_peg_empty="no"
  fi
  bandwidth_lines="$(grep -E 'pci 0000:0[0-9]:00\.0: .*available PCIe bandwidth|pci 0000:03:00\.0: .*available PCIe bandwidth' "${kernel_file}" 2>/dev/null || true)"

  {
    echo "## BIOS / PCIe Topology"
    echo
    echo "- Board: ${board_vendor:-unknown} ${board_name:-unknown}"
    echo "- BIOS: ${bios_version:-unknown} (${bios_date:-unknown})"
    echo "- CPU PEG root port appears empty: ${cpu_peg_empty}"
    if [ -n "${gpu_bridge}" ]; then
      echo "- GPU PCIe tree path: ${gpu_bridge}"
    fi
    if [ -n "${bandwidth_lines}" ]; then
      echo
      printf '%s\n' '```text'
      printf '%s\n' "${bandwidth_lines}"
      printf '%s\n' '```'
      echo
    fi
    if printf '%s\n' "${bandwidth_lines}" | grep -Eq '03:00\.0: .*x4 link .*capable of .*x16 link'; then
      echo "Likely cluster:"
      echo "- Firmware/kernel enumeration places the RTX GPU on a x4 negotiated path while reporting x16 capability. Combined with an empty CPU PEG root port, verify the physical slot, riser, and BIOS lane allocation before chasing driver behavior."
      echo
    fi
  } >>"${SUMMARY_FILE}"
}

render_nvidia_freeze_signals() {
  local mmap_files
  local fault_files
  local fault_regex
  local mmap_line_regex
  local mmap_matches
  local mmap_line_count
  local mmap_burst_count
  local mmap_burst_summary
  local fault_matches
  local fault_count

  mmap_files=(
    "${COMMANDS_DIR}/journal-current-warn.txt"
    "${COMMANDS_DIR}/journal-prev-warn.txt"
    "${COMMANDS_DIR}/journal-prev2-warn.txt"
  )

  fault_files=(
    "${COMMANDS_DIR}/journal-current-warn.txt"
    "${COMMANDS_DIR}/journal-prev-warn.txt"
    "${COMMANDS_DIR}/journal-prev2-warn.txt"
    "${COMMANDS_DIR}/journal-kernel-current.txt"
    "${COMMANDS_DIR}/nvidia-smi.txt"
  )

  mmap_line_regex="nvrm: vm: invalid mmap"
  fault_regex="nvrm: xid|nvidia-drm.*error|gpu has fallen off|nvidia-smi has failed|failed to initialize nvml"

  mmap_matches="$(collect_matches "${mmap_line_regex}" "${mmap_files[@]}")"
  mmap_line_count="$(printf '%s\n' "${mmap_matches}" | sed '/^$/d' | wc -l | tr -d ' ')"
  mmap_burst_summary="$(collect_nvidia_invalid_mmap_bursts "${mmap_files[@]}")"
  mmap_burst_count="$(printf '%s\n' "${mmap_burst_summary}" | sed '/^$/d' | wc -l | tr -d ' ')"
  fault_matches="$(collect_matches "${fault_regex}" "${fault_files[@]}")"
  fault_count="$(printf '%s\n' "${fault_matches}" | sed '/^$/d' | wc -l | tr -d ' ')"

  {
    echo "## NVIDIA Freeze Signals"
    echo
    echo "- Invalid-mmap lines: ${mmap_line_count}"
    echo "- Invalid-mmap burst windows: ${mmap_burst_count}"
    echo "- Other NVIDIA fault indicators: ${fault_count}"
    echo

    if [ "${mmap_burst_count}" -gt 0 ] || [ "${fault_count}" -gt 0 ]; then
      echo "Likely cluster:"
      if [ "${mmap_burst_count}" -gt 0 ]; then
        echo "- Repeated NVIDIA VM invalid-mmap bursts were captured, which is consistent with a GPU/userspace memory-mapping failure and can precede a full display freeze."
      fi
      if [ "${fault_count}" -gt 0 ]; then
        echo "- Additional NVIDIA fault markers are present beyond normal module-load noise."
      fi
      echo
      printf '%s\n' '```text'
      if [ -n "${mmap_burst_summary}" ]; then
        printf '%s\n' "${mmap_burst_summary}" | sed "s|${COMMANDS_DIR}/||g" | sed -n '1,12p'
      fi
      if [ -n "${fault_matches}" ]; then
        printf '%s\n' "${fault_matches}" | sed "s|${COMMANDS_DIR}/||g" | sed -n '1,8p'
      fi
      printf '%s\n' '```'
      echo
    fi
  } >>"${SUMMARY_FILE}"
}

render_mount_state() {
  local root_options
  local home_options
  local root_mode
  local home_mode
  local btrfs_error_line
  local mount_lines
  local btrfs_counters_present

  root_options="$(extract_findmnt_options "/")"
  home_options="$(extract_findmnt_options "/home")"
  root_mode="$(mount_mode_from_options "${root_options}")"
  home_mode="$(mount_mode_from_options "${home_options}")"
  btrfs_error_line="$(grep -nEm1 'BTRFS info .* errs:' "${COMMANDS_DIR}/journal-kernel-current.txt" 2>/dev/null || true)"

  mount_lines=""
  if [ -f "${COMMANDS_DIR}/findmnt.txt" ]; then
    mount_lines="$(
      awk '
        {
          mount_target = $1
          sub(/^[^/]+/, "", mount_target)
          if (mount_target == "/" || mount_target == "/home") {
            print "findmnt.txt:" FNR ":" $0
          }
        }
      ' \
        "${COMMANDS_DIR}/findmnt.txt" 2>/dev/null
    )"
  fi

  btrfs_counters_present="no"
  if [ -n "${btrfs_error_line}" ]; then
    btrfs_counters_present="yes"
  fi

  {
    echo "## Mount State"
    echo
    echo "- Root mount mode: ${root_mode}"
    echo "- Home mount mode: ${home_mode}"
    echo "- Persistent Btrfs device counters captured: ${btrfs_counters_present}"
    echo

    if [ "${root_mode}" = "ro" ] || [ "${home_mode}" = "ro" ] || [ -n "${btrfs_error_line}" ]; then
      echo "Likely cluster:"
      if [ "${root_mode}" = "ro" ] || [ "${home_mode}" = "ro" ]; then
        echo "- Root/home are mounted read-only in this snapshot; filesystem state is degraded right now."
      fi
      if [ -n "${btrfs_error_line}" ]; then
        echo "- Btrfs device error counters are still non-zero, so the earlier storage corruption history is unresolved."
      fi
      echo
      printf '%s\n' '```text'
      if [ -n "${mount_lines}" ]; then
        printf '%s\n' "${mount_lines}"
      fi
      if [ -n "${btrfs_error_line}" ]; then
        printf '%s\n' "${btrfs_error_line}" | sed "s|${COMMANDS_DIR}/||g"
      fi
      printf '%s\n' '```'
      echo
    fi
  } >>"${SUMMARY_FILE}"
}

render_package_footprint() {
  local rpm_package_count
  local flatpak_app_count
  local flatpak_runtime_count
  local snap_app_count

  rpm_package_count="$(count_payload_lines "${COMMANDS_DIR}/rpm-installed-packages.txt")"
  flatpak_app_count="$(count_payload_lines "${COMMANDS_DIR}/flatpak-installed-apps.txt")"
  flatpak_runtime_count="$(count_payload_lines "${COMMANDS_DIR}/flatpak-installed-runtimes.txt")"
  snap_app_count="$(count_payload_lines "${COMMANDS_DIR}/snap-installed.txt" '^Name[[:space:]]+Version[[:space:]]+Rev[[:space:]]+Tracking[[:space:]]+Publisher[[:space:]]+Notes$')"

  {
    echo "## Package Footprint"
    echo
    echo "- RPM packages: ${rpm_package_count}"
    echo "- Flatpak apps: ${flatpak_app_count}"
    echo "- Flatpak runtimes: ${flatpak_runtime_count}"
    echo "- Snap apps: ${snap_app_count}"
    echo

    if [ "${rpm_package_count}" -gt 0 ] || [ "${flatpak_app_count}" -gt 0 ] || [ "${flatpak_runtime_count}" -gt 0 ] || [ "${snap_app_count}" -gt 0 ]; then
      echo "Likely cluster:"
      echo "- Package inventory was captured in the crash snapshot, so tachometer can display the installed-software footprint alongside the active debug signals."
      echo
    else
      echo "No package inventory commands returned data."
      echo
    fi
  } >>"${SUMMARY_FILE}"
}

render_language_footprint() {
  local python_package_count
  local python_virtualenv_count
  local node_global_package_count
  local node_project_count
  local go_cached_module_count
  local go_module_root_count

  python_package_count="$(count_payload_lines "${COMMANDS_DIR}/python-default-packages.txt")"
  python_virtualenv_count="$(count_payload_lines "${COMMANDS_DIR}/python-virtualenvs.txt")"
  node_global_package_count="$(count_payload_lines "${COMMANDS_DIR}/node-global-packages.txt")"
  node_project_count="$(count_payload_lines "${COMMANDS_DIR}/node-project-manifests.txt")"
  go_cached_module_count="$(count_payload_lines "${COMMANDS_DIR}/go-cached-modules.txt")"
  go_module_root_count="$(count_payload_lines "${COMMANDS_DIR}/go-module-roots.txt")"

  {
    echo "## Language Footprint"
    echo
    echo "- Python packages (default interpreter): ${python_package_count}"
    echo "- Python virtualenvs: ${python_virtualenv_count}"
    echo "- Node global packages: ${node_global_package_count}"
    echo "- Node projects: ${node_project_count}"
    echo "- Go cached modules: ${go_cached_module_count}"
    echo "- Go module/work roots: ${go_module_root_count}"
    echo

    if [ "${python_package_count}" -gt 0 ] || [ "${python_virtualenv_count}" -gt 0 ] || [ "${node_global_package_count}" -gt 0 ] || [ "${node_project_count}" -gt 0 ] || [ "${go_cached_module_count}" -gt 0 ] || [ "${go_module_root_count}" -gt 0 ]; then
      echo "Likely cluster:"
      echo "- Development-language package and environment counts were captured so tachometer can show Python, Node, and Go footprint alongside the system package totals."
      echo
    else
      echo "No Python, Node, or Go footprint commands returned data."
      echo
    fi
  } >>"${SUMMARY_FILE}"
}

render_runtime_profile_wayland_gpu() {
  local focus_files
  local codium_regex
  local wayland_regex
  local session_regex
  local nvidia_fault_regex
  local nvidia_mmap_summary
  local memory_fault_regex
  local memory_fault_matches
  local nvml_regex
  local codium_matches
  local wayland_matches
  local session_matches
  local nvidia_fault_matches
  local codium_count
  local wayland_count
  local session_count
  local nvidia_fault_count
  local nvidia_mmap_burst_count
  local memory_fault_count
  local nvml_fail_count
  local session_type
  local wayland_display
  local display_name
  local codium_gpu_disabled
  local nvidia_smi_state

  focus_files=(
    "${COMMANDS_DIR}/dmesg.txt"
    "${COMMANDS_DIR}/journal-current-warn.txt"
    "${COMMANDS_DIR}/journal-prev-warn.txt"
    "${COMMANDS_DIR}/journal-prev2-warn.txt"
    "${COMMANDS_DIR}/journal-kernel-current.txt"
    "${COMMANDS_DIR}/coredump-codium.txt"
  )

  codium_regex="traps: codium|codium\\[[0-9]+\\].*(trap int3|invalid opcode|general protection fault)|process [0-9]+ \\(codium\\) of user [0-9]+ dumped core|/usr/share/codium/codium.*sig(segv|trap|ill)"
  wayland_regex="connection to xwayland lost|invalid sequence for vsync frame info|xwayland|wayland"
  session_regex="process [0-9]+ \\(gnome-shell\\) of user [0-9]+ dumped core|org\\.gnome\\.Shell@wayland\\.service: (main process exited|failed with result)|the wayland connection broke|user@[0-9]+\\.service: main process exited, code=dumped|process [0-9]+ \\(gnome-session-i\\) of user [0-9]+ dumped core"
  nvidia_fault_regex="nvrm: xid|nvidia-drm.*error|gpu has fallen off"
  memory_fault_regex="corrupted page table|bad pagetable|oops:|exited with irqs disabled"
  nvml_regex="failed to initialize nvml|nvidia-smi has failed|driver/library version mismatch"

  codium_matches="$(collect_matches "${codium_regex}" "${focus_files[@]}")"
  wayland_matches="$(collect_matches "${wayland_regex}" "${focus_files[@]}")"
  session_matches="$(collect_matches "${session_regex}" "${COMMANDS_DIR}/journal-current-warn.txt" "${COMMANDS_DIR}/journal-prev-warn.txt" "${COMMANDS_DIR}/journal-prev2-warn.txt")"
  nvidia_fault_matches="$(collect_matches "${nvidia_fault_regex}" "${focus_files[@]}" "${COMMANDS_DIR}/nvidia-smi.txt")"
  nvidia_mmap_summary="$(collect_nvidia_invalid_mmap_bursts "${COMMANDS_DIR}/journal-current-warn.txt" "${COMMANDS_DIR}/journal-prev-warn.txt" "${COMMANDS_DIR}/journal-prev2-warn.txt")"
  memory_fault_matches="$(collect_matches "${memory_fault_regex}" "${COMMANDS_DIR}/journal-current-warn.txt" "${COMMANDS_DIR}/journal-prev-warn.txt" "${COMMANDS_DIR}/journal-prev2-warn.txt" "${COMMANDS_DIR}/journal-kernel-current.txt")"

  codium_count="$(printf '%s\n' "${codium_matches}" | sed '/^$/d' | wc -l | tr -d ' ')"
  wayland_count="$(printf '%s\n' "${wayland_matches}" | sed '/^$/d' | wc -l | tr -d ' ')"
  session_count="$(printf '%s\n' "${session_matches}" | sed '/^$/d' | wc -l | tr -d ' ')"
  nvidia_fault_count="$(printf '%s\n' "${nvidia_fault_matches}" | sed '/^$/d' | wc -l | tr -d ' ')"
  nvidia_mmap_burst_count="$(printf '%s\n' "${nvidia_mmap_summary}" | sed '/^$/d' | wc -l | tr -d ' ')"
  memory_fault_count="$(printf '%s\n' "${memory_fault_matches}" | sed '/^$/d' | wc -l | tr -d ' ')"
  nvml_fail_count="$(count_matches "${nvml_regex}" "${COMMANDS_DIR}/nvidia-smi.txt" "${focus_files[@]}")"

  session_type="$(read_kv_value "${COMMANDS_DIR}/session-env.txt" "XDG_SESSION_TYPE")"
  wayland_display="$(read_kv_value "${COMMANDS_DIR}/session-env.txt" "WAYLAND_DISPLAY")"
  display_name="$(read_kv_value "${COMMANDS_DIR}/session-env.txt" "DISPLAY")"

  if [ -f "${COMMANDS_DIR}/vscodium-argv-json.txt" ] && grep -Eiq '"disable-hardware-acceleration"\s*:\s*true' "${COMMANDS_DIR}/vscodium-argv-json.txt"; then
    codium_gpu_disabled="yes"
  elif [ -f "${COMMANDS_DIR}/vscodium-argv-json.txt" ]; then
    codium_gpu_disabled="no"
  else
    codium_gpu_disabled="unknown"
  fi

  if [ -f "${COMMANDS_DIR}/nvidia-smi.txt" ] && grep -Eiq "${nvml_regex}" "${COMMANDS_DIR}/nvidia-smi.txt"; then
    nvidia_smi_state="failed"
  elif [ -f "${COMMANDS_DIR}/nvidia-smi.txt" ] && grep -Eiq 'NVIDIA-SMI[[:space:]]+[0-9]+|Driver Version:[[:space:]]*[0-9]+' "${COMMANDS_DIR}/nvidia-smi.txt"; then
    nvidia_smi_state="ok"
  elif [ -f "${COMMANDS_DIR}/nvidia-smi.txt" ]; then
    nvidia_smi_state="unknown"
  else
    nvidia_smi_state="not captured"
  fi

  {
    echo "## Runtime/Profile/Wayland-GPU Triage"
    echo
    echo "- Session type: ${session_type:-unknown}"
    echo "- Wayland display: ${wayland_display:-unknown}"
    echo "- X display: ${display_name:-unknown}"
    echo "- nvidia-smi state: ${nvidia_smi_state}"
    echo "- VSCodium GPU acceleration disabled in argv.json: ${codium_gpu_disabled}"
    echo "- Codium/Electron crash indicators: ${codium_count}"
    echo "- Wayland/Xwayland instability indicators: ${wayland_count}"
    echo "- Compositor/session crash indicators: ${session_count}"
    echo "- NVIDIA fault indicators: ${nvidia_fault_count}"
    echo "- NVIDIA invalid-mmap burst windows: ${nvidia_mmap_burst_count}"
    echo "- Kernel memory fault indicators: ${memory_fault_count}"
    echo "- NVML failure indicators: ${nvml_fail_count}"
    echo

    if [ "${codium_count}" -gt 0 ] || [ "${wayland_count}" -gt 0 ] || [ "${session_count}" -gt 0 ] || [ "${nvidia_fault_count}" -gt 0 ] || [ "${nvidia_mmap_burst_count}" -gt 0 ] || [ "${memory_fault_count}" -gt 0 ]; then
      echo "Likely cluster:"
      if [ "${codium_count}" -gt 0 ] && [ "${wayland_count}" -gt 0 ]; then
        echo "- Electron/Codium instability on the active display stack (Wayland/Xwayland path)."
      elif [ "${codium_count}" -gt 0 ]; then
        echo "- Codium runtime/profile instability (not yet isolated to GPU path)."
      elif [ "${wayland_count}" -gt 0 ]; then
        echo "- Display stack instability even without direct Codium traps."
      fi
      if [ "${session_count}" -gt 0 ]; then
        echo "- Wayland compositor/session crash indicators are present, so the failure is not limited to Codium itself."
      fi
      if [ "${nvidia_mmap_burst_count}" -gt 0 ]; then
        echo "- Repeated NVIDIA VM invalid-mmap bursts were captured, which is a stronger freeze indicator than normal module-load messages."
      fi
      if [ "${memory_fault_count}" -gt 0 ]; then
        echo "- Kernel page-table faults were recorded under GUI workloads, so this is not consistent with a single app-profile problem."
      fi
      if [ "${nvml_fail_count}" -gt 0 ]; then
        echo "- NVIDIA userspace/runtime health issue is present (nvidia-smi/NVML failure)."
      fi
      echo
      printf '%s\n' '```text'
      printf '%s\n' "${memory_fault_matches}" | sed "s|${COMMANDS_DIR}/||g" | sed -n '1,8p'
      printf '%s\n' "${codium_matches}" | sed "s|${COMMANDS_DIR}/||g" | sed -n '1,12p'
      printf '%s\n' "${wayland_matches}" | sed "s|${COMMANDS_DIR}/||g" | sed -n '1,8p'
      printf '%s\n' "${session_matches}" | sed "s|${COMMANDS_DIR}/||g" | sed -n '1,8p'
      printf '%s\n' "${nvidia_mmap_summary}" | sed "s|${COMMANDS_DIR}/||g" | sed -n '1,8p'
      printf '%s\n' "${nvidia_fault_matches}" | sed "s|${COMMANDS_DIR}/||g" | sed -n '1,8p'
      printf '%s\n' '```'
      echo
    fi

    echo "Suggested fix path (safe and reversible):"
    echo "1. Reduce GPU/Wayland pressure in the affected apps first:"
    echo "   - Prefer per-app X11 fallback or disabled GPU paths inside the current Wayland session."
    echo "2. Isolate Codium runtime vs profile inside the current session:"
    echo "   - codium --ozone-platform=x11 --disable-gpu --disable-extensions --user-data-dir /tmp/codium-clean-profile"
    echo "3. Treat Firefox/WebRender and Chromium/Electron as equal suspects when kernel page-table faults are present:"
    echo "   - Per-app X11 fallback is a better next test than Codium-only tuning."
    echo "4. If the clean Codium run is stable, disable GPU acceleration permanently via ~/.config/VSCodium/argv.json:"
    echo "   - { \"disable-hardware-acceleration\": true, \"ozone-platform-hint\": \"x11\" }"
    echo "5. If multiple GPU-accelerated apps still crash, escalate to display/session stack mitigation rather than app-profile cleanup."
    echo "6. Keep storage checks in the background:"
    echo "   - btrfs scrub status /"
    echo
  } >>"${SUMMARY_FILE}"
}

render_header
render_collection_health
render_suspend_triage
render_resume_context
render_recent_reboot_triage
render_historical_coredump_trends
render_xorg_comparison_readiness
render_bios_pcie_topology
render_nvidia_freeze_signals
render_gpu_pcie_link_evaluation
render_gpu_pcie_load_probe
render_mount_state
render_package_footprint
render_language_footprint

append_pattern_section "Kernel Panic Signals" "kernel panic|not syncing|panic:"
append_pattern_section "Call Trace Signals" "call trace|rip:|backtrace:"
append_pattern_section_from_files "Kernel Sanitizer Signals" "ubsan:|kasan:|kmsan:|------------\\[ cut here \\]------------" "${COMMANDS_DIR}/journal-current-warn.txt" "${COMMANDS_DIR}/journal-prev-warn.txt" "${COMMANDS_DIR}/journal-prev2-warn.txt" "${COMMANDS_DIR}/journal-kernel-current.txt"
append_pattern_section_from_files "Kernel Memory Fault Signals" "corrupted page table|bad pagetable|oops:|exited with irqs disabled" "${COMMANDS_DIR}/journal-current-warn.txt" "${COMMANDS_DIR}/journal-prev-warn.txt" "${COMMANDS_DIR}/journal-prev2-warn.txt" "${COMMANDS_DIR}/journal-kernel-current.txt"
append_pattern_section_from_files "Compiler/Build Stability Signals" "internal compiler error|/usr/libexec/gcc/.*/cc1|comm: cc1|terminated abnormally without generating a coredump" "${COMMANDS_DIR}/coredump-list.txt" "${COMMANDS_DIR}/journal-current-warn.txt" "${COMMANDS_DIR}/journal-prev-warn.txt" "${COMMANDS_DIR}/journal-prev2-warn.txt" "${COMMANDS_DIR}/journal-kernel-current.txt"
append_pattern_section "OOM Signals" "out of memory|oom-kill|killed process [0-9]+"
append_pattern_section "GPU/Display Signals" "amdgpu|nouveau|nvidia|i915|gpu hang|nvrm: xid"
append_pattern_section "Storage/Filesystem Signals" "i/o error|blk_update_request|btrfs|xfs|ext4-fs error|nvme.*error"
append_pattern_section "Thermal/Hardware Signals" "mce|hardware error|thermal|overheat|watchdog|hard lockup|soft lockup"
append_pattern_section "Segfault Signals" "segfault|general protection fault|invalid opcode"
render_runtime_profile_wayland_gpu

{
  echo "## Next Steps"
  echo
  echo "1. Validate whether repeated signals appear across multiple snapshots."
  echo "2. Correlate suspicious timestamps with user actions (suspend, browser, updates, gaming, etc)."
  echo "3. If needed, capture another snapshot immediately after reproducing."
  echo
} >>"${SUMMARY_FILE}"

echo "Analysis written to ${SUMMARY_FILE}"
