#!/usr/bin/env bash
set -u -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
ARTIFACTS_DIR="${ROOT_DIR}/artifacts"

usage() {
  cat <<'EOF'
Usage: ./scripts/analyze_snapshot.sh [snapshot_dir]

Analyze a snapshot generated by collect_snapshot.sh.
If snapshot_dir is omitted, the latest snapshot is used.
EOF
}

if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
  usage
  exit 0
fi

if [ $# -gt 1 ]; then
  usage >&2
  exit 1
fi

if [ $# -eq 1 ]; then
  SNAPSHOT_DIR="$1"
else
  if [ -L "${ARTIFACTS_DIR}/latest" ] || [ -d "${ARTIFACTS_DIR}/latest" ]; then
    SNAPSHOT_DIR="$(cd "${ARTIFACTS_DIR}" && pwd)/$(readlink "${ARTIFACTS_DIR}/latest")"
  else
    SNAPSHOT_DIR="$(ls -1dt "${ARTIFACTS_DIR}"/snapshot-* 2>/dev/null | head -n 1 || true)"
  fi
fi

if [ -z "${SNAPSHOT_DIR}" ] || [ ! -d "${SNAPSHOT_DIR}" ]; then
  echo "No snapshot found to analyze." >&2
  exit 1
fi

COMMANDS_DIR="${SNAPSHOT_DIR}/commands"
SUMMARY_FILE="${SNAPSHOT_DIR}/analysis-summary.md"

if [ ! -d "${COMMANDS_DIR}" ]; then
  echo "Invalid snapshot: missing commands directory: ${COMMANDS_DIR}" >&2
  exit 1
fi

mapfile -t LOG_FILES < <(find "${COMMANDS_DIR}" -maxdepth 1 -type f | sort)

if [ "${#LOG_FILES[@]}" -eq 0 ]; then
  echo "No command output files found in ${COMMANDS_DIR}" >&2
  exit 1
fi

render_header() {
  {
    echo "# Crash Analysis Summary"
    echo
    echo "- Snapshot: ${SNAPSHOT_DIR}"
    echo "- Generated: $(date --iso-8601=seconds)"
    echo
  } >"${SUMMARY_FILE}"
}

render_collection_health() {
  local failures
  failures="$(grep -H '^# Exit status: [1-9]' "${COMMANDS_DIR}"/*.txt 2>/dev/null || true)"

  {
    echo "## Collection Health"
    if [ -n "${failures}" ]; then
      echo
      echo "Some collection commands returned non-zero exit statuses."
      echo "This is usually due to permissions or missing commands."
      echo
      printf '%s\n' '```text'
      echo "${failures}" | sed "s|${COMMANDS_DIR}/||g"
      printf '%s\n' '```'
    else
      echo
      echo "All collection commands exited with status 0."
    fi
    echo
  } >>"${SUMMARY_FILE}"
}

append_pattern_section() {
  local label="$1"
  local regex="$2"
  local matches
  local count

  matches="$(grep -HnEi "${regex}" "${LOG_FILES[@]}" 2>/dev/null || true)"
  count="$(printf '%s\n' "${matches}" | sed '/^$/d' | wc -l | tr -d ' ')"

  {
    echo "## ${label}"
    echo
    echo "- Matches: ${count}"
    if [ "${count}" -gt 0 ]; then
      echo
      printf '%s\n' '```text'
      printf '%s\n' "${matches}" | sed "s|${COMMANDS_DIR}/||g" | sed -n '1,25p'
      printf '%s\n' '```'
    fi
    echo
  } >>"${SUMMARY_FILE}"
}

render_header
render_collection_health

append_pattern_section "Kernel Panic Signals" "kernel panic|not syncing|panic:"
append_pattern_section "Call Trace Signals" "call trace|rip:|backtrace:"
append_pattern_section "OOM Signals" "out of memory|oom-kill|killed process [0-9]+"
append_pattern_section "GPU/Display Signals" "amdgpu|nouveau|nvidia|i915|gpu hang|xid"
append_pattern_section "Storage/Filesystem Signals" "i/o error|blk_update_request|btrfs|xfs|ext4-fs error|nvme.*error"
append_pattern_section "Thermal/Hardware Signals" "mce|hardware error|thermal|overheat|watchdog|hard lockup|soft lockup"
append_pattern_section "Segfault Signals" "segfault|general protection fault|invalid opcode"

{
  echo "## Next Steps"
  echo
  echo "1. Validate whether repeated signals appear across multiple snapshots."
  echo "2. Correlate suspicious timestamps with user actions (suspend, browser, updates, gaming, etc)."
  echo "3. If needed, capture another snapshot immediately after reproducing."
  echo
} >>"${SUMMARY_FILE}"

echo "Analysis written to ${SUMMARY_FILE}"
